# Fake Azure Storage Account Key to trigger secret scanning
DefaultEndpointsProtocol=https;AccountName=fakestorageaccount;AccountKey=1q2w3e4r5t6y7u8i9o0pEXAMPLEKEY1234567890qwertyuiop


adafruit_io_key="uruehrguier9erugbeg8bvhdfv"
	databricks_access_token="ireviehrv8rvneuveruvenrurvneurr8"
