name: Migrate Secret Scanning Alerts
on:
  issues:
    types: [opened]

jobs:
  migrate-secrets:
    if: github.event.issue.title == 'Migrate Secret Scanning Alerts'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh

    - name: Install GEI Utility
      run: |
        gh extension install github/gh-gei

    - name: Migrate Secret Scanning Alerts
      run: |
        gh gei migrate-secret-alerts --  --repo ${{ github.event.issue.body }}
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Comment on issue
      run: gh issue comment ${{ github.event.issue.number }} --body "Secret scanning migration complete!"
