name: Enforce Repo Naming Convention and Create Repository

on:
  issues:
    types: [opened]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Name
        id: validate
        run: |
          REPO_NAME="${{ github.event.issue.title }}"
          if [[ ! $REPO_NAME =~ ^mgm-.*$ ]]; then
            echo "The repository name '${REPO_NAME}' does not follow the naming convention. It must start with 'mgm-'."
            echo "comment=The repository name '${REPO_NAME}' does not follow the naming convention. It must start with 'mgm-'." >> $GITHUB_ENV
            exit 1
          else
            echo "The repository name '${REPO_NAME}' follows the naming convention."
            echo "comment=The repository name '${REPO_NAME}' follows the naming convention." >> $GITHUB_ENV
          fi

      - name: Comment on Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ env.comment }}"
            })

  create-repo:
    runs-on: ubuntu-latest
    needs: check-repo-name
    if: success()  # Only run if the naming convention is followed
    steps:
      - name: Create Repository
        uses: peter-evans/create-or-update-repo@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.issue.title }}
          description: "Repository created for ${{ github.event.issue.title }}"
