name: Repository Naming Convention Check

on:
  repository_dispatch:
    types: [check_repo_name]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository Naming Convention
        env:
          REPO_NAME: ${{ github.event.client_payload.repo_name }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Token with permissions to delete repos
        run: |
          if [[ "$REPO_NAME" != mgm-* ]]; then
            echo "Repository name '${REPO_NAME}' does not follow the naming convention (should start with 'mgm-')."
            echo "Deleting repository '${REPO_NAME}'..."
            
            # Delete the repository using GitHub API
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository_owner }}/$REPO_NAME"
          else
            echo "Repository name '${REPO_NAME}' follows the naming convention."

