name: Enforce Repo Naming Convention and Create Repository

on:
  issues:
    types: [opened]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Name
        id: validate
        run: |
          REPO_NAME="${{ github.event.issue.title }}"
          if [[ ! $REPO_NAME =~ ^mgm-.*$ ]]; then
            echo "The repository name '${REPO_NAME}' does not follow the naming convention. It must start with 'mgm-'."
            exit 1
          else
            echo "The repository name '${REPO_NAME}' follows the naming convention."
          fi

  create-repo:
    runs-on: ubuntu-latest
    needs: check-repo-name
    if: success()  # Only run if the naming convention is followed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Create Repository
        run: |
          ORGANIZATION_NAME="RepoNamingConventionDemo"  # Set your organization name here
          gh repo create "${ORGANIZATION_NAME}/${{ github.event.issue.title }}" --description "Repository created for ${{ github.event.issue.title }}" --public
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
