name: Enforce Repo Naming Convention

on:
  issues:
    types: [opened]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository Name
        id: validate
        run: |
          REPO_NAME="${{ github.event.issue.title }}"
          if [[ ! $REPO_NAME =~ ^mgm-.*$ ]]; then
           echo "The repository name '${REPO_NAME}' does not follow the naming convention. It must start with 'mgm-'."
           echo "::set-output name=comment::The repository name '${REPO_NAME}' does not follow the naming convention. It must start with 'mgm-'."
           exit 1
          else
           echo "The repository name '${REPO_NAME}' follows the naming convention."
           echo "::set-output name=comment::The repository name '${REPO_NAME}' follows the naming convention."
          fi


      - name: Comment on Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.validate.outputs.comment }}"
            })
