name: Enforce Repository Naming Convention

on:
  repository:
    types: [created]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check if repository name starts with "mgm-"
      run: |
        REPO_NAME="${{ github.event.repository.name }}"
        if [[ "$REPO_NAME" != mgm-* ]]; then
          echo "Repository name does not start with 'mgm-'. Deleting repository..."
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}
        else
          echo "Repository name is valid."
        fi
