name: Repository Naming Convention Check

on:
  repository:
    types: [created]

jobs:
  check-repo-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository Naming Convention
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          if [[ "${REPO_NAME}" != mgm-* ]]; then
            echo "Repository name '${REPO_NAME}' does not follow the naming convention (should start with 'mgm-')."
            # Add any additional action here, such as failure or notification
          else
            echo "Repository name '${REPO_NAME}' follows the naming convention."
          fi
